name: Release Changes

on:
  push:
    branches: [main]
    tags: [v**]

env:
  BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}

jobs:
  quality_checks:
    uses: ./.github/workflows/quality_checks.yml
  
  tag_release:
    needs: quality_checks
    runs-on: ubuntu-latest
    outputs:
      spec_version: ${{ steps.output_spec_version.outputs.SPEC_VERSION }}
      change_set_version: ${{ steps.output_change_set_version.outputs.CHANGE_SET_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0
      
      - name: Install asdf
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.11.3
        
      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-
      
      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.11.3
        env:
            PYTHON_CONFIGURE_OPTS: --enable-shared
      
      - name: Install Dependencies
        run: make install
      
      - name: Set SPEC_VERSION for merges to main
        run: echo "SPEC_VERSION=$(poetry run python scripts/calculate_version.py)" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'
      
      - name: Set SPEC_VERSION for tags
        run: echo "SPEC_VERSION=${{  github.ref_name }}" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      
      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.SPEC_VERSION }}
          commit: ${{  github.sha }}
          body: |
            ## Commit message
            ${{ github.event.head_commit.message }}
            ## Info
            [See code diff](${{ github.event.compare }})
            [Release workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            It was initialized by [${{ github.event.sender.login }}](${{ github.event.sender.html_url }})
      
      - name: Output SPEC_VERSION
        id: output_spec_version
        run: echo SPEC_VERSION=${{ env.SPEC_VERSION }} >> $GITHUB_OUTPUT

      - name: Output Change Set Version
        id: output_change_set_version
        shell: bash
        run: |
          TIMESTAMP=$(date +%s)
          VERSION=$(echo ${{ env.SPEC_VERSION }} | tr . -)
          echo CHANGE_SET_VERSION=$VERSION-$TIMESTAMP >> $GITHUB_OUTPUT

  release_ci_resources_dev:
    needs: tag_release
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: dev-ci
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: ci-resources
      template: ./cloudformation/ci_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
  
  release_account_resources_dev:
    needs: [tag_release, release_ci_resources_dev]
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: dev-account
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: account-resources
      template: ./cloudformation/account_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
    
  release_ci_resources_ref:
    needs: [tag_release, release_ci_resources_dev, release_account_resources_dev]
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: ref-ci
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: ci-resources
      template: ./cloudformation/ci_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.REF_CLOUD_FORMATION_DEPLOY_ROLE }}
  
  release_account_resources_ref:
    needs: [tag_release, release_ci_resources_dev, release_account_resources_dev]
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: ref-account
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: account-resources
      template: ./cloudformation/account_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.REF_CLOUD_FORMATION_DEPLOY_ROLE }}
  
  release_ci_resources_qa:
    needs: [tag_release, release_ci_resources_dev, release_account_resources_dev]
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: qa-ci
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: ci-resources
      template: ./cloudformation/ci_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.QA_CLOUD_FORMATION_DEPLOY_ROLE }}
  
  release_account_resources_qa:
    needs: [tag_release, release_ci_resources_dev, release_account_resources_dev]
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: qa-account
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: account-resources
      template: ./cloudformation/account_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.QA_CLOUD_FORMATION_DEPLOY_ROLE }}

  release_ci_resources_int:
    needs: [tag_release, release_ci_resources_qa, release_account_resources_qa]
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: int-ci
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: ci-resources
      template: ./cloudformation/ci_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.INT_CLOUD_FORMATION_DEPLOY_ROLE }}
  
  release_account_resources_int:
    needs: [tag_release, release_ci_resources_qa, release_account_resources_qa]
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: int-account
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: account-resources
      template: ./cloudformation/account_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.INT_CLOUD_FORMATION_DEPLOY_ROLE }}

  release_ci_resources_prod:
    needs: [tag_release, release_ci_resources_int, release_account_resources_int]
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: prod-ci
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: ci-resources
      template: ./cloudformation/ci_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.PROD_CLOUD_FORMATION_DEPLOY_ROLE }}
  
  release_account_resources_prod:
    needs: [tag_release, release_ci_resources_int, release_account_resources_int]
    uses: ./.github/workflows/cloudformation.yml
    with:
      target_environment: prod-account
      version: ${{ needs.tag_release.outputs.spec_version }}
      change_set_version: ${{ needs.tag_release.outputs.change_set_version }}
      stack_name: account-resources
      template: ./cloudformation/account_resources.yml
      capabilities: CAPABILITY_IAM
      execute_change_set: true
    secrets:
      cf_deploy_role: ${{ secrets.PROD_CLOUD_FORMATION_DEPLOY_ROLE }}
